### ISSUE TITLE
Peer to Peer Code Review for Benjamin Agyekum Portfolio

### ISSUE THREAD

**Issue by AsimKhan2019** [hislordshipprof/Hello-Microverse#9]
We shall be reviewing Benjamin's work today for the morning session.

**Comment by Markotweyo** [comment]
- script.js file seems to be confusing on its specific role, please I suggest we get sometime to clarify it for me

**Comment by AsimKhan2019** [comment]
The code is well documented and the portfolio looks very good and professional.

**Comment by AsimKhan2019** [comment]
I am now closing this issue.
